config/routes.rb
Rails.application.routes.draw do
  resources :players

  root 'players#index'

  get "individual/teller"
  post "individual/teller"

  get "individual/other"
  post "individual/other"

  get "individual/confirm"
  post "individual/confirm"

  get "result/result"
  post "result/result"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/player.rb
class Player < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/individual_controller.rb
class IndividualController < ApplicationController
  def index

  end

  def teller
    name1 = params[:name1]
    name2 = params[:name2]
    name3 = params[:name3]
    name4 = params[:name4]
    name5 = params[:name5]
    name6 = params[:name6]
  end

  def other

  end

  def confirm

  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: [:show, :edit, :update, :destroy]

  # GET /players
  # GET /players.json
  def index
    @players = Player.all
  end

  # GET /players/1
  # GET /players/1.json
  def show
  end

  # GET /players/new
  def new
    @player = Player.new
  end

  # GET /players/1/edit
  def edit
  end

  # POST /players
  # POST /players.json
  def create
    @player = Player.new(player_params)

    respond_to do |format|
      if @player.save
        format.html { redirect_to @player, notice: 'Player was successfully created.' }
        format.json { render :show, status: :created, location: @player }
      else
        format.html { render :new }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1
  # PATCH/PUT /players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to @player, notice: 'Player was successfully updated.' }
        format.json { render :show, status: :ok, location: @player }
      else
        format.html { render :edit }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player.destroy
    respond_to do |format|
      format.html { redirect_to players_url, notice: 'Player was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def player_params
      params.require(:player).permit(:val1, :val2, :val3, :val4, :val5, :val6)
    end
end

app/controllers/result_controller.rb
class ResultController < ApplicationController
  def index

  end

  def result

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/individual/confirm.html.erb
<% current_number = params[:current_number].to_i %>
<% number = params[:number].to_i %>
<% story = params[:story] %>


<% if number >= 6 then%>
<% name6 = params[:name6]%>
<% name6card = params[:name6card]%>
<% end %>
<% if number >= 5 then%>
<% name5 = params[:name5]%>
<% name5card = params[:name5card]%>
<% end %>
<% if number >= 4 then%>
<% name4 = params[:name4]%>
<% name4card = params[:name4card]%>
<% end %>
<% name3 = params[:name3]%>
<% name3card = params[:name3card]%>
<% name2 = params[:name2]%>
<% name2card = params[:name2card] %>
<% name1 = params[:name1]%>
<% name1card = params[:name1card]%>

<% if current_number == 1 then%>
  <% current_name = name2 %>
  <% name1select = params[:name1select][:val] %>
<% elsif current_number == 2 then%>
  <% current_name = name3 %>
  <% name1select = params[:name1select] %>
  <% name2select = params[:current_select][:val] %>
<% elsif current_number == 3 then %>
<% current_name = name4 %>
<% name1select = params[:name1select] %>
<% name2select = params[:name2select] %>
<% name3select = params[:current_select][:val] %>
<% elsif current_number == 4 then %>
<% current_name = name5 %>
<% name1select = params[:name1select] %>
<% name2select = params[:name2select] %>
<% name3select = params[:name3select] %>
<% name4select = params[:current_select][:val] %>
<% elsif current_number == 5 then %>
<% current_name = name6 %>
<% name1select = params[:name1select] %>
<% name2select = params[:name2select] %>
<% name3select = params[:name3select] %>
<% name4select = params[:name4select] %>
<% name5select = params[:current_select][:val] %>
<% end %>



<form action="../individual/other" name="to_start" method="get">
<h1>次は <%=current_name%> の番です</h1>

  <%= hidden_field_tag :number, "#{number}" %>
  <%= hidden_field_tag :story, "#{story}" %>
  <%= hidden_field_tag :current_number, "#{current_number}" %>

  <% if current_number == 1 then %>
  <%= hidden_field_tag :name1select, "#{name1select}" %>
  <% elsif current_number == 2 then %>
  <%= hidden_field_tag :name1select, "#{name1select}" %>
  <%= hidden_field_tag :name2select, "#{name2select}" %>
  <% elsif current_number == 3 then %>
  <%= hidden_field_tag :name1select, "#{name1select}" %>
  <%= hidden_field_tag :name2select, "#{name2select}" %>
  <%= hidden_field_tag :name3select, "#{name3select}" %>
  <% elsif current_number == 4 then %>
  <%= hidden_field_tag :name1select, "#{name1select}" %>
  <%= hidden_field_tag :name2select, "#{name2select}" %>
  <%= hidden_field_tag :name3select, "#{name3select}" %>
  <%= hidden_field_tag :name4select, "#{name4select}" %>
  <% elsif current_number == 5 then %>
  <%= hidden_field_tag :name1select, "#{name1select}" %>
  <%= hidden_field_tag :name2select, "#{name2select}" %>
  <%= hidden_field_tag :name3select, "#{name3select}" %>
  <%= hidden_field_tag :name4select, "#{name4select}" %>
  <%= hidden_field_tag :name5select, "#{name5select}" %>
  <% end %>

  <% if number >= 6 then %>
  <%= hidden_field_tag :name6card, "#{name6card}" %>
  <%= hidden_field_tag :name5card, "#{name5card}" %>
  <%= hidden_field_tag :name4card, "#{name4card}" %>
  <%= hidden_field_tag :name6, "#{name6}" %>
  <%= hidden_field_tag :name5, "#{name5}" %>
  <%= hidden_field_tag :name4, "#{name4}" %>
  <% elsif number >= 5 then %>
  <%= hidden_field_tag :name5card, "#{name5card}" %>
  <%= hidden_field_tag :name4card, "#{name4card}" %>
  <%= hidden_field_tag :name5, "#{name5}" %>
  <%= hidden_field_tag :name4, "#{name4}" %>
  <% elsif number >= 4 then %>
  <%= hidden_field_tag :name4card, "#{name4card}" %>
  <%= hidden_field_tag :name4, "#{name4}" %>
  <% end %>
  <%= hidden_field_tag :name3card, "#{name3card}" %>
  <%= hidden_field_tag :name2card, "#{name2card}" %>
  <%= hidden_field_tag :name1card, "#{name1card}" %>
  <%= hidden_field_tag :name3, "#{name3}" %>
  <%= hidden_field_tag :name2, "#{name2}" %>
  <%= hidden_field_tag :name1, "#{name1}" %>
  <%= submit_tag "確認" ,id: "submit" %>

  <end>

app/views/individual/other.html.erb
<% current_number = params[:current_number].to_i+1 %>
<% number = params[:number].to_i %>
<% story = params[:story] %>

<% if number >= 6 then%>
<% name6 = params[:name6]%>
<% name6card = params[:name6card]%>
<% end %>
<% if number >= 5 then%>
<% name5 = params[:name5]%>
<% name5card = params[:name5card]%>
<% end %>
<% if number >= 4 then%>
<% name4 = params[:name4]%>
<% name4card = params[:name4card]%>
<% end %>
<% name3 = params[:name3]%>
<% name3card = params[:name3card]%>
<% name2 = params[:name2]%>
<% name2card = params[:name2card] %>
<% name1 = params[:name1]%>
<% name1card = params[:name1card]%>


<% if current_number == 2 then%>
  <% current_card = name2card.delete("[").delete("]").split(",") %>
  <% current_name = name2 %>
  <% name1select = params[:name1select] %>
<% elsif current_number == 3 then %>
<% current_card = name3card.delete("[").delete("]").split(",") %>
<% current_name = name3 %>
<% name1select = params[:name1select] %>
<% name2select = params[:name2select] %>
<% elsif current_number == 4 then %>
<% current_card = name4card.delete("[").delete("]").split(",") %>
<% current_name = name4 %>
<% name1select = params[:name1select] %>
<% name2select = params[:name2select] %>
<% name3select = params[:name3select] %>
<% elsif current_number == 5 then %>
<% current_card = name5card.delete("[").delete("]").split(",") %>
<% current_name = name5 %>
<% name1select = params[:name1select] %>
<% name2select = params[:name2select] %>
<% name3select = params[:name3select] %>
<% name4select = params[:name4select] %>
<% elsif current_number == 6 then %>
<% current_card = name6card.delete("[").delete("]").split(",") %>
<% current_name = name6 %>
<% name1select = params[:name1select] %>
<% name2select = params[:name2select] %>
<% name3select = params[:name3select] %>
<% name4select = params[:name4select] %>
<% name5select = params[:name5select] %>
<% end %>


<% if number != current_number %>
<form action="../individual/confirm" name="to_start" method="get">
<% elsif number == current_number %>
<form action="../result/result" name="to_start" method="get">
<% end %>
<h2>下のお題を想像できるような絵を一枚選択してください</h2>
<h1>お題： <%= story %> </h1>
<h2><%= current_name %> のカード一覧</h2>
<label>
<%= radio_button 'current_select',"val",current_card.slice(0), required: true %>
<%= image_tag "cards/card#{"%05d" % current_card.slice(0)}.png", :size => '224x312' %>
</label><label>
<%= radio_button 'current_select',"val",current_card.slice(1), required: true %>
<%= image_tag "cards/card#{"%05d" % current_card.slice(1)}.png", :size => '224x312' %>
</label><label>
<%= radio_button 'current_select',"val",current_card.slice(2), required: true %>
<%= image_tag "cards/card#{"%05d" % current_card.slice(2)}.png", :size => '224x312' %>
</label><br><label>
<%= radio_button 'current_select',"val",current_card.slice(3), required: true %>
<%= image_tag "cards/card#{"%05d" % current_card.slice(3)}.png", :size => '224x312' %>
</label><label>
<%= radio_button 'current_select',"val",current_card.slice(4), required: true %>
<%= image_tag "cards/card#{"%05d" % current_card.slice(4)}.png", :size => '224x312' %>
</label><label>
<%= radio_button 'current_select',"val",current_card.slice(5), required: true %>
<%= image_tag "cards/card#{"%05d" % current_card.slice(5)}.png", :size => '224x312' %>
</label>

<%= hidden_field_tag :number, "#{number}" %>
<%= hidden_field_tag :story, "#{story}" %>
<%= hidden_field_tag :current_number, "#{current_number}" %>


<% if current_number == 2 then %>
<%= hidden_field_tag :name1select, "#{name1select}" %>
<% elsif current_number == 3 then %>
<%= hidden_field_tag :name1select, "#{name1select}" %>
<%= hidden_field_tag :name2select, "#{name2select}" %>
<% elsif current_number == 4 then %>
<%= hidden_field_tag :name1select, "#{name1select}" %>
<%= hidden_field_tag :name2select, "#{name2select}" %>
<%= hidden_field_tag :name3select, "#{name3select}" %>
<% elsif current_number == 5 then %>
<%= hidden_field_tag :name1select, "#{name1select}" %>
<%= hidden_field_tag :name2select, "#{name2select}" %>
<%= hidden_field_tag :name3select, "#{name3select}" %>
<%= hidden_field_tag :name4select, "#{name4select}" %>
<% elsif current_number == 6 then %>
<%= hidden_field_tag :name1select, "#{name1select}" %>
<%= hidden_field_tag :name2select, "#{name2select}" %>
<%= hidden_field_tag :name3select, "#{name3select}" %>
<%= hidden_field_tag :name4select, "#{name4select}" %>
<%= hidden_field_tag :name5select, "#{name5select}" %>
<% end %>


<% if number >= 6 then %>
<%= hidden_field_tag :name6card, "#{name6card}" %>
<%= hidden_field_tag :name5card, "#{name5card}" %>
<%= hidden_field_tag :name4card, "#{name4card}" %>
<%= hidden_field_tag :name6, "#{name6}" %>
<%= hidden_field_tag :name5, "#{name5}" %>
<%= hidden_field_tag :name4, "#{name4}" %>
<% elsif number >= 5 then %>
<%= hidden_field_tag :name5card, "#{name5card}" %>
<%= hidden_field_tag :name4card, "#{name4card}" %>
<%= hidden_field_tag :name5, "#{name5}" %>
<%= hidden_field_tag :name4, "#{name4}" %>
<% elsif number >= 4 then %>
<%= hidden_field_tag :name4card, "#{name4card}" %>
<%= hidden_field_tag :name4, "#{name4}" %>
<% end %>
<%= hidden_field_tag :name3card, "#{name3card}" %>
<%= hidden_field_tag :name2card, "#{name2card}" %>
<%= hidden_field_tag :name1card, "#{name1card}" %>
<%= hidden_field_tag :name3, "#{name3}" %>
<%= hidden_field_tag :name2, "#{name2}" %>
<%= hidden_field_tag :name1, "#{name1}" %>
<%= submit_tag "送信" ,id: "submit" %>

<end>



<br>
参加者一覧<br>
<% if number >= 6 %>
<%= name6 %><br>
<% end %>
<% if number >= 5 %>
<%= name5 %><br>
<% end %>
<% if number >= 4 %>
<%= name4 %><br>
<% end %>
<%= name3 %><br>
<%= name2 %><br>
<%= name1 %>

app/views/individual/teller.html.erb
<% if params[:name6] != "" then %>
  <% name6 = params[:name6] %>
  <% name5 = params[:name5] %>
  <% name4 = params[:name4] %>
  <% number = 6 %>
  <% cards = (1..508).to_a.shuffle[0...number*6] %>
  <% name6card= cards.slice!(0..5)%>
  <% name5card= cards.slice!(0..5)%>
  <% name4card= cards.slice!(0..5)%>
<% elsif params[:name5] != "" then %>
  <% name5 = params[:name5] %>
  <% name4 = params[:name4] %>
  <% number = 5 %>
  <% cards = (1..508).to_a.shuffle[0...number*6] %>
  <% name5card= cards.slice!(0..5)%>
  <% name4card= cards.slice!(0..5)%>
<% elsif params[:name4] != "" then %>
  <% name4 = params[:name4] %>
  <% number = 4 %>
  <% cards = (1..508).to_a.shuffle[0...number*6] %>
  <% name4card= cards.slice!(0..5)%>
<% elsif params[:name3] != "" then %>
  <% number = 3 %>
  <% cards = (1..508).to_a.shuffle[0...number*6] %>
<% end %>

<% name3 = params[:name3] %>
<% name2 = params[:name2] %>
<% name1 = params[:name1] %>
<% name3card= cards.slice!(0..5)%>
<% name2card= cards.slice!(0..5)%>
<% name1card= cards.slice(0..5)%>

<% current_number = 1 %>

<h1><%= name1 %>はストーリーテラーです</h1>
下の６枚の絵から一枚を選択し、その絵柄を想像させるようなテキストを
入力してください<br>
それが終わったら下の送信ボタンを押してください<br>

※他プレイヤーに画像を見られた場合、ページをリロードすることで画像の更新ができます<br>


<form action="../individual/confirm" name="to_start" method="get">
  <input type="text" name="story" style="width:300px;height:50px;" required/><br>
  <h2>あなたのカード一覧</h2>
  <label>
  <%= radio_button 'name1select',"val",name1card.slice(0), required: true%>
  <%= image_tag "cards/card#{"%05d" % name1card.slice(0)}.png", :size => '224x312' %>
  </label><label>
  <%= radio_button 'name1select',"val",name1card.slice(1), required: true%>
  <%= image_tag "cards/card#{"%05d" % name1card.slice(1)}.png", :size => '224x312' %>
</label><label>
  <%= radio_button 'name1select',"val",name1card.slice(2), required: true%>
  <%= image_tag "cards/card#{"%05d" % name1card.slice(2)}.png", :size => '224x312' %>
</label><br><label>
  <%= radio_button 'name1select',"val",name1card.slice(3), required: true%>
  <%= image_tag "cards/card#{"%05d" % name1card.slice(3)}.png", :size => '224x312' %>
</label><label>
  <%= radio_button 'name1select',"val",name1card.slice(4), required: true%>
  <%= image_tag "cards/card#{"%05d" % name1card.slice(4)}.png", :size => '224x312' %>
</label><label>
  <%= radio_button 'name1select',"val",name1card.slice(5), required: true%>
  <%= image_tag "cards/card#{"%05d" % name1card.slice(5)}.png", :size => '224x312' %>
  </label>

  <%= hidden_field_tag :number, "#{number}" %>
  <%= hidden_field_tag :current_number, "#{current_number}" %>

  <% if number >= 6 then %>
  <%= hidden_field_tag :name6card, "#{name6card}" %>
  <%= hidden_field_tag :name5card, "#{name5card}" %>
  <%= hidden_field_tag :name4card, "#{name4card}" %>
  <%= hidden_field_tag :name6, "#{name6}" %>
  <%= hidden_field_tag :name5, "#{name5}" %>
  <%= hidden_field_tag :name4, "#{name4}" %>
  <% elsif number >= 5 then %>
  <%= hidden_field_tag :name5card, "#{name5card}" %>
  <%= hidden_field_tag :name4card, "#{name4card}" %>
  <%= hidden_field_tag :name5, "#{name5}" %>
  <%= hidden_field_tag :name4, "#{name4}" %>
  <% elsif number >= 4 then %>
  <%= hidden_field_tag :name4card, "#{name4card}" %>
  <%= hidden_field_tag :name4, "#{name4}" %>
  <% end %>
  <%= hidden_field_tag :name3card, "#{name3card}" %>
  <%= hidden_field_tag :name2card, "#{name2card}" %>
  <%= hidden_field_tag :name1card, "#{name1card}" %>
  <%= hidden_field_tag :name3, "#{name3}" %>
  <%= hidden_field_tag :name2, "#{name2}" %>
  <%= hidden_field_tag :name1, "#{name1}" %>
  <%= submit_tag "送信" ,id: "submit" %>

<end>
<br>

参加者一覧<br>
<% if number >= 6 %>
<%= name6 %><br>
<% end %>
<% if number >= 5 %>
<%= name5 %><br>
<% end %>
<% if number >= 4 %>
<%= name4 %><br>
<% end %>
<%= name3 %><br>
<%= name2 %><br>
<%= name1 %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dixit</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/players/_form.html.erb
<%= form_with(model: player, local: true) do |form| %>
  <% if player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% player.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :val1 %>
    <%= form.number_field :val1, id: :player_val1 %>
  </div>

  <div class="field">
    <%= form.label :val2 %>
    <%= form.number_field :val2, id: :player_val2 %>
  </div>

  <div class="field">
    <%= form.label :val3 %>
    <%= form.number_field :val3, id: :player_val3 %>
  </div>

  <div class="field">
    <%= form.label :val4 %>
    <%= form.number_field :val4, id: :player_val4 %>
  </div>

  <div class="field">
    <%= form.label :val5 %>
    <%= form.number_field :val5, id: :player_val5 %>
  </div>

  <div class="field">
    <%= form.label :val6 %>
    <%= form.number_field :val6, id: :player_val6 %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/players/edit.html.erb
<h1>Editing Player</h1>

<%= render 'form', player: @player %>

<%= link_to 'Show', @player %> |
<%= link_to 'Back', players_path %>

app/views/players/index.html.erb
<p id="notice"><%= notice %></p>

<h1>プレイ人数を選択</h1>
最低3人の名前を入力してください<br>
名前は上から詰めて入力してください<br>

<form action="../individual/teller" name="to_start" method="get" onsubmit="return check_form()">
  <input type="text" name="name1" id="n1" /><br>
  <input type="text" name="name2" id="n2" /><br>
  <input type="text" name="name3" id="n3" /><br>
  <input type="text" name="name4" id="n4" /><br>
  <input type="text" name="name5" id="n5" /><br>
  <input type="text" name="name6" id="n6" />
  <input type="submit" value="ゲームスタート" >
</form>

<br>

app/views/players/new.html.erb
<h1>New Player</h1>

<%= render 'form', player: @player %>

<%= link_to 'Back', players_path %>

app/views/players/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Val1:</strong>
  <%= @player.val1 %>
</p>

<p>
  <strong>Val2:</strong>
  <%= @player.val2 %>
</p>

<p>
  <strong>Val3:</strong>
  <%= @player.val3 %>
</p>

<p>
  <strong>Val4:</strong>
  <%= @player.val4 %>
</p>

<p>
  <strong>Val5:</strong>
  <%= @player.val5 %>
</p>

<p>
  <strong>Val6:</strong>
  <%= @player.val6 %>
</p>

<%= link_to 'Edit', edit_player_path(@player) %> |
<%= link_to 'Back', players_path %>